- cmdarr:
    - mpc
    - current
  opts: 
    align: l
- cmdarr:
    - $GOPATH/src/github.com/pentla/barms/cmds/bspwm-tri/bspwm-tri
  opts: 
    align: c
    sub: true
- cmdarr:
    - date
    - +%A, %B %d %l:%M
  opts: 
    align: r
    mon: 1
